language: perl
sudo: false

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - cpanm --quiet --notest --skip-satisfied DBD::mysql
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-recommend .
  - cover -delete
script:
  - perl Build.PL
  - ./Build build
  - cover -test -report codecov
