language: perl
sudo: false

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - cover -delete
env:
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,inc"
after_success:
  - cover -report codecov
